name: Refresh cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://zuzugo.vercel.app/api/fetchNewHouses' \
          --header 'X-API-SECRET: ${{ secrets.API_SECRET_KEY }}'
